In [14]:
from absenteeism_module import *

In [15]:
pd.read_csv('Absenteeism_new_data.csv')

,ID,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets
0,22,27,01/06/2018,179,26,30,237.656,19,3,0,0
1,10,7,04/06/2018,361,52,28,237.656,27,1,1,4
2,14,23,06/06/2018,155,12,34,237.656,25,1,2,0
3,17,25,08/06/2018,179,22,40,237.656,22,2,2,0
4,14,10,08/06/2018,155,12,34,237.656,25,1,2,0
5,28,11,11/06/2018,225,26,28,237.656,24,1,1,2
6,16,7,13/06/2018,118,15,46,275.089,25,1,2,0
7,22,27,13/06/2018,179,26,30,275.089,19,3,0,0
8,34,26,15/06/2018,118,10,37,275.089,28,1,0,0
9,34,10,20/06/2018,118,10,37,275.089,28,1,0,0
10,23,22,21/06/2018,378,49,36,275.089,21,1,2,4
11,36,19,21/06/2018,118,13,50,275.089,31,1,1,0
12,12,19,22/06/2018,233,51,31,275.089,21,2,1,8
13,22,27,22/06/2018,179,26,30,275.089,19,3,0,0
14,2,0,25/06/2018,235,29,48,275.089,33,1,1,5
15,21,0,28/06/2018,268,11,33,275.089,25,2,0,0
16,36,19,28/06/2018,118,13,50,275.089,31,1,1,0
17,22,13,28/06/2018,179,26,30,275.089,19,3,0,0
18,15,28,28/06/2018,291,31,40,275.089,25,1,1,1
19,22,13,02/07/2018,179,26,30,275.089,19,3,0,0
20,34,25,02/07/2018,118,10,37,275.089,28,1,0,0
21,12,22,05/07/2018,233,51,31,275.089,21,2,1,8
22,34,8,06/07/2018,118,10,37,275.089,28,1,0,0
23,34,10,11/07/2018,118,10,37,275.089,28,1,0,0
24,12,22,11/07/2018,233,51,31,275.089,21,2,1,8
25,5,26,11/07/2018,235,20,43,264.604,38,1,1,0
26,12,19,13/07/2018,233,51,31,264.604,21,2,1,8
27,9,6,16/07/2018,228,14,58,264.604,22,1,2,1
28,34,28,16/07/2018,118,10,37,264.604,28,1,0,0
29,9,6,17/07/2018,228,14,58,264.604,22,1,2,1
30,6,22,17/07/2018,189,29,33,264.604,25,1,2,2
31,34,23,18/07/2018,118,10,37,264.604,28,1,0,0
32,10,22,18/07/2018,361,52,28,264.604,27,1,1,4
33,28,22,18/07/2018,225,26,28,264.604,24,1,1,2
34,13,13,23/07/2018,369,17,31,264.604,25,1,3,0
35,11,14,24/07/2018,289,36,33,264.604,30,1,2,1
36,1,11,24/07/2018,235,11,37,264.604,29,3,1,1
37,4,0,24/07/2018,118,14,40,271.219,34,1,1,8
38,8,0,25/07/2018,231,35,39,271.219,35,1,2,2
39,35,0,27/07/2018,179,45,53,271.219,25,1,1,1

In [16]:
model = absenteeism_model('model', 'scaler')

/Users/Jonas/opt/anaconda3/lib/python3.7/site-packages/sklearn/base.py:318: UserWarning: Trying to unpickle estimator LogisticRegression from version 0.19.1 when using version 0.22. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/Users/Jonas/opt/anaconda3/lib/python3.7/site-packages/sklearn/base.py:318: UserWarning: Trying to unpickle estimator StandardScaler from version 0.19.1 when using version 0.22. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)

In [17]:
# Helps to load and clean data by uploading the csv file directly
model.load_and_clean_data('Absenteeism_new_data.csv')

In [18]:
# feeds the data to the model
model.predicted_outputs()

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Transportation Expense,Age,Body Mass Index,Education,Children,Pet,Probability,Prediction
0,0,0.0,0,1,6,179,30,19,1,0,0,0.122799,0
1,1,0.0,0,0,6,361,28,27,0,1,4,0.873392,1
2,0,0.0,0,1,6,155,34,25,0,2,0,0.268305,0
3,0,0.0,0,1,6,179,40,22,1,2,0,0.196385,0
4,1,0.0,0,0,6,155,34,25,0,2,0,0.723502,1
5,1,0.0,0,0,6,225,28,24,0,1,2,0.716891,1
6,1,0.0,0,0,6,118,46,25,0,2,0,0.570524,1
7,0,0.0,0,1,6,179,30,19,1,0,0,0.122799,0
8,0,0.0,0,1,6,118,37,28,0,0,0,0.134118,0
9,1,0.0,0,0,6,118,37,28,0,0,0,0.525007,1
10,0,0.0,0,1,6,378,36,21,0,2,4,0.454998,0
11,0,0.0,1,0,6,118,50,31,0,1,0,0.644742,1
12,0,0.0,1,0,6,233,31,21,1,1,8,0.351108,0
13,0,0.0,0,1,6,179,30,19,1,0,0,0.122799,0
14,0,0.0,0,0,6,235,48,33,0,1,5,0.096533,0
15,0,0.0,0,0,6,268,33,25,1,0,0,0.189479,0
16,0,0.0,1,0,6,118,50,31,0,1,0,0.644742,1
17,1,0.0,0,0,6,179,30,19,1,0,0,0.499738,0
18,0,0.0,0,1,6,291,40,25,0,1,1,0.389531,0
19,1,0.0,0,0,7,179,30,19,1,0,0,0.500161,1
20,0,0.0,0,1,7,118,37,28,0,0,0,0.134315,0
21,0,0.0,0,1,7,233,31,21,1,1,8,0.051367,0
22,1,0.0,0,0,7,118,37,28,0,0,0,0.525428,1
23,1,0.0,0,0,7,118,37,28,0,0,0,0.525428,1
24,0,0.0,0,1,7,233,31,21,1,1,8,0.051367,0
25,0,0.0,0,1,7,235,43,38,0,1,0,0.512352,1
26,0,0.0,1,0,7,233,31,21,1,1,8,0.351493,0
27,1,0.0,0,0,7,228,58,22,0,2,1,0.633385,1
28,0,0.0,0,1,7,118,37,28,0,0,0,0.134315,0
29,1,0.0,0,0,7,228,58,22,0,2,1,0.633385,1
30,0,0.0,0,1,7,189,33,25,0,2,2,0.244943,0
31,0,0.0,0,1,7,118,37,28,0,0,0,0.134315,0
32,0,0.0,0,1,7,361,28,27,0,1,4,0.491962,0
33,0,0.0,0,1,7,225,28,24,0,1,2,0.262240,0
34,1,0.0,0,0,7,369,31,25,0,3,0,0.966560,1
35,1,0.0,0,0,7,289,33,30,0,2,1,0.912399,1
36,1,0.0,0,0,7,235,37,29,1,1,1,0.746598,1
37,0,0.0,0,0,7,118,40,34,0,1,8,0.023090,0
38,0,0.0,0,0,7,231,39,35,0,2,2,0.295647,0
39,0,0.0,0,0,7,179,53,25,0,1,1,0.076450,0

In [19]:
# import to build a bridge between python and mysql
import pymysql

In [20]:
# Creating a connection
conn = pymysql.connect(database = 'predicted_outputs', user = 'root')

In [21]:
# Creating a Cursor to be able to write SQL queries in Jupyter
cursor = conn.cursor()

## Checkpoint 'df_new_obs'

In [22]:
df_new_obs = model.predicted_outputs()
df_new_obs

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Transportation Expense,Age,Body Mass Index,Education,Children,Pet,Probability,Prediction
0,0,0.0,0,1,6,179,30,19,1,0,0,0.122799,0
1,1,0.0,0,0,6,361,28,27,0,1,4,0.873392,1
2,0,0.0,0,1,6,155,34,25,0,2,0,0.268305,0
3,0,0.0,0,1,6,179,40,22,1,2,0,0.196385,0
4,1,0.0,0,0,6,155,34,25,0,2,0,0.723502,1
5,1,0.0,0,0,6,225,28,24,0,1,2,0.716891,1
6,1,0.0,0,0,6,118,46,25,0,2,0,0.570524,1
7,0,0.0,0,1,6,179,30,19,1,0,0,0.122799,0
8,0,0.0,0,1,6,118,37,28,0,0,0,0.134118,0
9,1,0.0,0,0,6,118,37,28,0,0,0,0.525007,1
10,0,0.0,0,1,6,378,36,21,0,2,4,0.454998,0
11,0,0.0,1,0,6,118,50,31,0,1,0,0.644742,1
12,0,0.0,1,0,6,233,31,21,1,1,8,0.351108,0
13,0,0.0,0,1,6,179,30,19,1,0,0,0.122799,0
14,0,0.0,0,0,6,235,48,33,0,1,5,0.096533,0
15,0,0.0,0,0,6,268,33,25,1,0,0,0.189479,0
16,0,0.0,1,0,6,118,50,31,0,1,0,0.644742,1
17,1,0.0,0,0,6,179,30,19,1,0,0,0.499738,0
18,0,0.0,0,1,6,291,40,25,0,1,1,0.389531,0
19,1,0.0,0,0,7,179,30,19,1,0,0,0.500161,1
20,0,0.0,0,1,7,118,37,28,0,0,0,0.134315,0
21,0,0.0,0,1,7,233,31,21,1,1,8,0.051367,0
22,1,0.0,0,0,7,118,37,28,0,0,0,0.525428,1
23,1,0.0,0,0,7,118,37,28,0,0,0,0.525428,1
24,0,0.0,0,1,7,233,31,21,1,1,8,0.051367,0
25,0,0.0,0,1,7,235,43,38,0,1,0,0.512352,1
26,0,0.0,1,0,7,233,31,21,1,1,8,0.351493,0
27,1,0.0,0,0,7,228,58,22,0,2,1,0.633385,1
28,0,0.0,0,1,7,118,37,28,0,0,0,0.134315,0
29,1,0.0,0,0,7,228,58,22,0,2,1,0.633385,1
30,0,0.0,0,1,7,189,33,25,0,2,2,0.244943,0
31,0,0.0,0,1,7,118,37,28,0,0,0,0.134315,0
32,0,0.0,0,1,7,361,28,27,0,1,4,0.491962,0
33,0,0.0,0,1,7,225,28,24,0,1,2,0.262240,0
34,1,0.0,0,0,7,369,31,25,0,3,0,0.966560,1
35,1,0.0,0,0,7,289,33,30,0,2,1,0.912399,1
36,1,0.0,0,0,7,235,37,29,1,1,1,0.746598,1
37,0,0.0,0,0,7,118,40,34,0,1,8,0.023090,0
38,0,0.0,0,0,7,231,39,35,0,2,2,0.295647,0
39,0,0.0,0,0,7,179,53,25,0,1,1,0.076450,0

## .execute()

In [12]:
query = 'SELECT * FROM predicted_outputs;'

In [13]:
cursor.execute(query) #execute moves the data to MySQL Workbench

0

they match, both MySQL and Jupyter has just an empty table, which is why it says 0 here. To change that, we need to continue and create a multiple row insert.

## Creating the INSERT Statement

In [39]:
insert_query = 'INSERT INTO predicted_outputs VALUES'

In [40]:
insert_query

'INSERT INTO predicted_outputs VALUES'

In [41]:
df_new_obs.shape

(40, 13)

In [42]:
df_new_obs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pet', 'Probability', 'Prediction'], dtype=object)

In [43]:
df_new_obs['Age'].head()

0    30
1    28
2    34
3    40
4    34
Name: Age, dtype: int64

In [44]:
for i in range(df_new_obs.shape[0]): #We want to go through every row of df_new_obs
    insert_query += '(' #start with an open parenthesis
    
    for j in range(df_new_obs.shape[1]): #for every column of our dataframe, we take the value and enter with a comma
        insert_query += str(df_new_obs[df_new_obs.columns.values[j]][i]) + ', '
    
    insert_query = insert_query[:-2] + '),' #removed the last two characters and replace with closed parenthesis and comma

In [45]:
insert_query

'INSERT INTO predicted_outputs VALUES(0, 0.0, 0, 1, 6, 179, 30, 19, 1, 0, 0, 0.12279926243494323, 0),(1, 0.0, 0, 0, 6, 361, 28, 27, 0, 1, 4, 0.8733923470447209, 1),(0, 0.0, 0, 1, 6, 155, 34, 25, 0, 2, 0, 0.2683049546034322, 0),(0, 0.0, 0, 1, 6, 179, 40, 22, 1, 2, 0, 0.1963853143922252, 0),(1, 0.0, 0, 0, 6, 155, 34, 25, 0, 2, 0, 0.7235017225544896, 1),(1, 0.0, 0, 0, 6, 225, 28, 24, 0, 1, 2, 0.7168905020985188, 1),(1, 0.0, 0, 0, 6, 118, 46, 25, 0, 2, 0, 0.5705238370679658, 1),(0, 0.0, 0, 1, 6, 179, 30, 19, 1, 0, 0, 0.12279926243494323, 0),(0, 0.0, 0, 1, 6, 118, 37, 28, 0, 0, 0, 0.13411805408968352, 0),(1, 0.0, 0, 0, 6, 118, 37, 28, 0, 0, 0, 0.5250065611752316, 1),(0, 0.0, 0, 1, 6, 378, 36, 21, 0, 2, 4, 0.4549980207286245, 0),(0, 0.0, 1, 0, 6, 118, 50, 31, 0, 1, 0, 0.6447416367376194, 1),(0, 0.0, 1, 0, 6, 233, 31, 21, 1, 1, 8, 0.35110766120784753, 0),(0, 0.0, 0, 1, 6, 179, 30, 19, 1, 0, 0, 0.12279926243494323, 0),(0, 0.0, 0, 0, 6, 235, 48, 33, 0, 1, 5, 0.09653346354354148, 0),(0, 0.0, 0, 0, 6, 268, 33, 25, 1, 0, 0, 0.1894785903905003, 0),(0, 0.0, 1, 0, 6, 118, 50, 31, 0, 1, 0, 0.6447416367376194, 1),(1, 0.0, 0, 0, 6, 179, 30, 19, 1, 0, 0, 0.49973827165859197, 0),(0, 0.0, 0, 1, 6, 291, 40, 25, 0, 1, 1, 0.38953149469289, 0),(1, 0.0, 0, 0, 7, 179, 30, 19, 1, 0, 0, 0.5001612226284466, 1),(0, 0.0, 0, 1, 7, 118, 37, 28, 0, 0, 0, 0.13431464561079212, 0),(0, 0.0, 0, 1, 7, 233, 31, 21, 1, 1, 8, 0.051366563789338106, 0),(1, 0.0, 0, 0, 7, 118, 37, 28, 0, 0, 0, 0.525428436293439, 1),(1, 0.0, 0, 0, 7, 118, 37, 28, 0, 0, 0, 0.525428436293439, 1),(0, 0.0, 0, 1, 7, 233, 31, 21, 1, 1, 8, 0.051366563789338106, 0),(0, 0.0, 0, 1, 7, 235, 43, 38, 0, 1, 0, 0.5123518738925141, 1),(0, 0.0, 1, 0, 7, 233, 31, 21, 1, 1, 8, 0.35149320375017246, 0),(1, 0.0, 0, 0, 7, 228, 58, 22, 0, 2, 1, 0.6333849402703989, 1),(0, 0.0, 0, 1, 7, 118, 37, 28, 0, 0, 0, 0.13431464561079212, 0),(1, 0.0, 0, 0, 7, 228, 58, 22, 0, 2, 1, 0.6333849402703989, 1),(0, 0.0, 0, 1, 7, 189, 33, 25, 0, 2, 2, 0.24494273576137351, 0),(0, 0.0, 0, 1, 7, 118, 37, 28, 0, 0, 0, 0.13431464561079212, 0),(0, 0.0, 0, 1, 7, 361, 28, 27, 0, 1, 4, 0.4919621401501115, 0),(0, 0.0, 0, 1, 7, 225, 28, 24, 0, 1, 2, 0.26224032774538253, 0),(1, 0.0, 0, 0, 7, 369, 31, 25, 0, 3, 0, 0.966560156232829, 1),(1, 0.0, 0, 0, 7, 289, 33, 30, 0, 2, 1, 0.9123989237228621, 1),(1, 0.0, 0, 0, 7, 235, 37, 29, 1, 1, 1, 0.7465975923060953, 1),(0, 0.0, 0, 0, 7, 118, 40, 34, 0, 1, 8, 0.0230895016874011, 0),(0, 0.0, 0, 0, 7, 231, 39, 35, 0, 2, 2, 0.2956474890457222, 0),(0, 0.0, 0, 0, 7, 179, 53, 25, 0, 1, 1, 0.07644956838010682, 0),'

In [46]:
insert_query = insert_query[:-1] +';'

In [47]:
insert_query

'INSERT INTO predicted_outputs VALUES(0, 0.0, 0, 1, 6, 179, 30, 19, 1, 0, 0, 0.12279926243494323, 0),(1, 0.0, 0, 0, 6, 361, 28, 27, 0, 1, 4, 0.8733923470447209, 1),(0, 0.0, 0, 1, 6, 155, 34, 25, 0, 2, 0, 0.2683049546034322, 0),(0, 0.0, 0, 1, 6, 179, 40, 22, 1, 2, 0, 0.1963853143922252, 0),(1, 0.0, 0, 0, 6, 155, 34, 25, 0, 2, 0, 0.7235017225544896, 1),(1, 0.0, 0, 0, 6, 225, 28, 24, 0, 1, 2, 0.7168905020985188, 1),(1, 0.0, 0, 0, 6, 118, 46, 25, 0, 2, 0, 0.5705238370679658, 1),(0, 0.0, 0, 1, 6, 179, 30, 19, 1, 0, 0, 0.12279926243494323, 0),(0, 0.0, 0, 1, 6, 118, 37, 28, 0, 0, 0, 0.13411805408968352, 0),(1, 0.0, 0, 0, 6, 118, 37, 28, 0, 0, 0, 0.5250065611752316, 1),(0, 0.0, 0, 1, 6, 378, 36, 21, 0, 2, 4, 0.4549980207286245, 0),(0, 0.0, 1, 0, 6, 118, 50, 31, 0, 1, 0, 0.6447416367376194, 1),(0, 0.0, 1, 0, 6, 233, 31, 21, 1, 1, 8, 0.35110766120784753, 0),(0, 0.0, 0, 1, 6, 179, 30, 19, 1, 0, 0, 0.12279926243494323, 0),(0, 0.0, 0, 0, 6, 235, 48, 33, 0, 1, 5, 0.09653346354354148, 0),(0, 0.0, 0, 0, 6, 268, 33, 25, 1, 0, 0, 0.1894785903905003, 0),(0, 0.0, 1, 0, 6, 118, 50, 31, 0, 1, 0, 0.6447416367376194, 1),(1, 0.0, 0, 0, 6, 179, 30, 19, 1, 0, 0, 0.49973827165859197, 0),(0, 0.0, 0, 1, 6, 291, 40, 25, 0, 1, 1, 0.38953149469289, 0),(1, 0.0, 0, 0, 7, 179, 30, 19, 1, 0, 0, 0.5001612226284466, 1),(0, 0.0, 0, 1, 7, 118, 37, 28, 0, 0, 0, 0.13431464561079212, 0),(0, 0.0, 0, 1, 7, 233, 31, 21, 1, 1, 8, 0.051366563789338106, 0),(1, 0.0, 0, 0, 7, 118, 37, 28, 0, 0, 0, 0.525428436293439, 1),(1, 0.0, 0, 0, 7, 118, 37, 28, 0, 0, 0, 0.525428436293439, 1),(0, 0.0, 0, 1, 7, 233, 31, 21, 1, 1, 8, 0.051366563789338106, 0),(0, 0.0, 0, 1, 7, 235, 43, 38, 0, 1, 0, 0.5123518738925141, 1),(0, 0.0, 1, 0, 7, 233, 31, 21, 1, 1, 8, 0.35149320375017246, 0),(1, 0.0, 0, 0, 7, 228, 58, 22, 0, 2, 1, 0.6333849402703989, 1),(0, 0.0, 0, 1, 7, 118, 37, 28, 0, 0, 0, 0.13431464561079212, 0),(1, 0.0, 0, 0, 7, 228, 58, 22, 0, 2, 1, 0.6333849402703989, 1),(0, 0.0, 0, 1, 7, 189, 33, 25, 0, 2, 2, 0.24494273576137351, 0),(0, 0.0, 0, 1, 7, 118, 37, 28, 0, 0, 0, 0.13431464561079212, 0),(0, 0.0, 0, 1, 7, 361, 28, 27, 0, 1, 4, 0.4919621401501115, 0),(0, 0.0, 0, 1, 7, 225, 28, 24, 0, 1, 2, 0.26224032774538253, 0),(1, 0.0, 0, 0, 7, 369, 31, 25, 0, 3, 0, 0.966560156232829, 1),(1, 0.0, 0, 0, 7, 289, 33, 30, 0, 2, 1, 0.9123989237228621, 1),(1, 0.0, 0, 0, 7, 235, 37, 29, 1, 1, 1, 0.7465975923060953, 1),(0, 0.0, 0, 0, 7, 118, 40, 34, 0, 1, 8, 0.0230895016874011, 0),(0, 0.0, 0, 0, 7, 231, 39, 35, 0, 2, 2, 0.2956474890457222, 0),(0, 0.0, 0, 0, 7, 179, 53, 25, 0, 1, 1, 0.07644956838010682, 0);'

In [48]:
# Moves the data to MySQL Workbench
cursor.execute(insert_query)

40

In [49]:
# we need to commit to add it to MySQL
conn.commit()

In [51]:
# Close the connection
conn.close()